# Generated by Django 4.0.2 on 2022-02-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('lat', models.IntegerField()),
                ('lon', models.IntegerField()),
            ],
        ),
    ]
