# Generated by Django 4.0.2 on 2022-02-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airsafeTrackingSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='time_stamp',
            field=models.DateTimeField(),
        ),
    ]
