# Generated by Django 4.0.2 on 2022-02-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airsafeTrackingSystem', '0002_alter_aircraft_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=6),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=6),
        ),
    ]
