# Generated by Django 4.0.2 on 2022-02-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airsafeTrackingSystem', '0003_alter_aircraft_lat_alter_aircraft_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='lat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='lon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
